### PR TITLE
Fix highlight persistence, add ability to retain multiple highlights

### PR DESCRIPTION
**Pull request by ghost**
* Program will now remember current document history of all highlights and keep them persisted on the screen

* Program now supports the ability to switch the context of labeling while still persisting the color-state of previous highlights

* TODO: bind color selection and label such that a label cannot be associated with 2 colors nor a color with 2 labels

### CODE REVIEW

**Review by keithudock — APPROVED** [review]
Radio button selects a default value in firefox but does not detect it when highlighting

**Review by tuj52136 — APPROVED** [review]
TODO: move color out of annotation

**Comment by tmarkn** [comment]
Working!

**Review by tmarkn — APPROVED** [review]
Working!

**Pull request merged**
